

-- 1- ACTIF_DATA_ET_DATE_ACTIVATION


-- 2- BUNDLE
LOAD DATA INPATH '/BUNDLE/201611/*' INTO TABLE OIC.TT_BUNDLE;
LOAD DATA INPATH '/BUNDLE/201612/*' INTO TABLE OIC.TT_BUNDLE;
LOAD DATA INPATH '/BUNDLE/201701/*' INTO TABLE OIC.TT_BUNDLE;
LOAD DATA INPATH '/BUNDLE/201702/*' INTO TABLE OIC.TT_BUNDLE;
LOAD DATA INPATH '/BUNDLE/201703/*' INTO TABLE OIC.TT_BUNDLE;
LOAD DATA INPATH '/BUNDLE/201704/*' INTO TABLE OIC.TT_BUNDLE;
             
-- 3- CDR	
-- 3-1- traffic_customer_cell

-- 3-2- traffic_customer


-- 4- DONNEES_HISTO_MENSUELLES


-- 5- ENTRANT	


-- 6- INFO_TERMINAUX	


-- 7- MSIM	


-- 8- RECHARGE	


-- 9- REFERENTIEL_TERMINAUX


-- 10- SORTANT


-- 11- SVA	


-- 12- TRANSACTION_OM
