
-- 1- ACTIF_DATA_ET_DATE_ACTIVATION
DROP TABLE IF EXISTS OIC.TT_ACTIF_DATA_ET_DATE_ACTIVATION;


-- 2- BUNDLE
DROP TABLE IF EXISTS OIC.TT_BUNDLE;


-- 3- CDR	
-- 3-1- traffic_customer_cell
DROP TABLE IF EXISTS OIC.TT_TRAFFIC_CUSTOMER_CELL;


-- 3-2- traffic_customer
DROP TABLE IF EXISTS OIC.TT_TRAFFIC_CUSTOMER;


-- 4- DONNEES_HISTO_MENSUELLES
DROP TABLE IF EXISTS OIC.TT_DONNEES_HISTO_MENSUELLES;


-- 5- ENTRANT	
DROP TABLE IF EXISTS OIC.TT_ENTRANT;


-- 6- INFO_TERMINAUX	
DROP TABLE IF EXISTS OIC.TT_INFO_TERMINAUX;


-- 7- MSIM	
DROP TABLE IF EXISTS OIC.TT_MSIM;


-- 8- RECHARGE	
DROP TABLE IF EXISTS OIC.TT_RECHARGE;


-- 9- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TT_REFERENTIEL_TERMINAUX;


-- 10- SORTANT
DROP TABLE IF EXISTS OIC.TT_SORTANT;


-- 11- SVA	
DROP TABLE IF EXISTS OIC.TT_SVA;


-- 12- TRANSACTION_OM
DROP TABLE IF EXISTS OIC.TT_TRANSACTION_OM;
