-- 1- ACTIF_DATA_ET_DATE_ACTIVATION
DROP TABLE IF EXISTS OIC.TT_ACTIF_DATA_ET_DATE_ACTIVATION;

-- 2- BUNDLE
DROP TABLE IF EXISTS OIC.TT_BUNDLE;
DROP TABLE IF EXISTS OIC.TT_BUNDLE_2;

-- 3- CDR	
-- 3-1- cdr_traffic_customer_cell
DROP TABLE IF EXISTS OIC.TT_CDR_TRAFFIC_CUSTOMER_CELL;

-- 3-2- traffic_customer
DROP TABLE IF EXISTS OIC.TT_CDR_TRAFFIC_CUSTOMER;

-- 3-3- Conversions_Id; Table = OIC.TT_CONVERSIONS_ID_*;
-- Table = OIC.TT_CONVERSIONS_ID_APN;
DROP TABLE IF EXISTS OIC.TT_CONVERSIONS_ID_APN;

-- Table = OIC.TT_CONVERSIONS_ID_APPLI;
DROP TABLE IF EXISTS OIC.TT_CONVERSIONS_ID_APPLI;

-- Table = OIC.TT_CONVERSIONS_ID_CUST_CONTACT;
DROP TABLE IF EXISTS OIC.TT_CONVERSIONS_ID_CUST_CONTACT;

-- Table = OIC.TT_CONVERSIONS_ID_GGSN;
DROP TABLE IF EXISTS OIC.TT_CONVERSIONS_ID_GGSN;

-- Table = OIC.TT_CONVERSIONS_ID_RAT;
DROP TABLE IF EXISTS OIC.TT_CONVERSIONS_ID_RAT;

-- Table = OIC.TT_CONVERSIONS_ID_CUST_MSISDN;
DROP TABLE IF EXISTS OIC.TT_CONVERSIONS_ID_CUST_MSISDN;

-- 3-4- Localisation_cellules; Table = OIC.TT_LOCALISATION_CELLULES;
DROP TABLE IF EXISTS OIC.TT_LOCALISATION_CELLULES;

-- 4- DONNEES_HISTO_MENSUELLES
DROP TABLE IF EXISTS OIC.TT_DONNEES_HISTO_MENSUELLES;

-- 5- ENTRANT	
DROP TABLE IF EXISTS OIC.TT_CDR_ENTRANT;

-- 6- INFO_TERMINAUX	
DROP TABLE IF EXISTS OIC.TT_INFO_TERMINAUX;

-- 7- MSIM	
DROP TABLE IF EXISTS OIC.TT_MSIM;

-- 8- RECHARGE	
DROP TABLE IF EXISTS OIC.TT_RECHARGE;
DROP TABLE IF EXISTS OIC.TT_RECHARGE_2;

-- 9- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TT_REFERENTIEL_TERMINAUX;

-- 10- SORTANT
DROP TABLE IF EXISTS OIC.TT_CDR_SORTANT;

-- 11- SVA	
DROP TABLE IF EXISTS OIC.TT_SVA;

-- 12- TRANSACTION_OM
DROP TABLE IF EXISTS OIC.TT_TRANSACTION_OM;

-----------------------------------------------------------
-----------------------------------------------------------
-- 13- Service Provider per Day
DROP TABLE IF EXISTS OIC.TT_customers_sp_day_201611;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_day_201612;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_day_201701;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_day_201702;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_day_201703;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_day_201704;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170508;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170509;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170510;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170511;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170512;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170513;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170514;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170515;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170516;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170517;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170518;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170519;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170520;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170521;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170522;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170523;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170524;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170525;

DROP TABLE IF EXISTS OIC.TT_customers_sp_day_20170526;

-- 14- Service Provider per month
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201611;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201612;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201701;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201702;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201703;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201704;
--
DROP TABLE IF EXISTS OIC.TT_customers_sp_month_201705;

------------------------------------------------------------
------------------------------------------------------------
-- 1- ACTIF_DATA_ET_DATE_ACTIVATION
DROP TABLE IF EXISTS OIC.TF_ACTIF_DATA_ET_DATE_ACTIVATION;
-- 2- BUNDLE
DROP TABLE IF EXISTS OIC.TF_BUNDLE;
-- 3- CDR	
-- 3-1- cdr_traffic_customer_cell
DROP TABLE IF EXISTS OIC.TF_CDR_TRAFFIC_CUSTOMER_CELL;
-- 3-2- traffic_customer
DROP TABLE IF EXISTS OIC.TF_CDR_TRAFFIC_CUSTOMER;
-- 3-3- Conversions_Id; Table = OIC.TF_CONVERSIONS_ID_*;
-- Table = OIC.TF_CONVERSIONS_ID_APN;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_APN;
-- Table = OIC.TF_CONVERSIONS_ID_APPLI;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_APPLI;
-- Table = OIC.TF_CONVERSIONS_ID_CUST_CONTACT;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_CUST_CONTACT;
-- Table = OIC.TF_CONVERSIONS_ID_GGSN;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_GGSN;
-- Table = OIC.TF_CONVERSIONS_ID_RAT;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_RAT;
-- Table = OIC.TF_CONVERSIONS_ID_CUST_MSISDN;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_CUST_MSISDN;
-- 3-4- Localisation_cellules; Table = OIC.TF_LOCALISATION_CELLULES;
DROP TABLE IF EXISTS OIC.TF_LOCALISATION_CELLULES;
-- 4- DONNEES_HISTO_MENSUELLES
DROP TABLE IF EXISTS OIC.TF_DONNEES_HISTO_MENSUELLES;
-- 5- ENTRANT	
DROP TABLE IF EXISTS OIC.TF_CDR_ENTRANT;
-- 6- INFO_TERMINAUX	
DROP TABLE IF EXISTS OIC.TF_INFO_TERMINAUX;
-- 7- MSIM	
DROP TABLE IF EXISTS OIC.TF_MSIM;
-- 8- RECHARGE	
DROP TABLE IF EXISTS OIC.TF_RECHARGE;
-- 9- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TF_REFERENTIEL_TERMINAUX;
-- 10- SORTANT
DROP TABLE IF EXISTS OIC.TF_CDR_SORTANT;
-- 11- SVA	
DROP TABLE IF EXISTS OIC.TF_SVA;
-- 12- TRANSACTION_OM
DROP TABLE IF EXISTS OIC.TF_TRANSACTION_OM;
-----------------------------------------------------------
-----------------------------------------------------------
-- Don't execute below queries else, we plan to delete all
-- fonctional tables
-----------------------------------------------------------
-----------------------------------------------------------
-- 13- Service Provider per Day
DROP TABLE IF EXISTS OIC.TF_customers_sp_day_201611;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_day_201612;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_day_201701;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_day_201702;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_day_201703;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_day_201704;
-- 14- Service Provider per month
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201611;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201612;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201701;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201702;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201703;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201704;
--
DROP TABLE IF EXISTS OIC.TF_customers_sp_month_201705;
--------------------------------------------------------------------
DROP TABLE IF EXISTS OIC.tf_actif_data_et_date_activation_10pct;
DROP TABLE IF EXISTS OIC.tf_bundle_10pct;
DROP TABLE IF EXISTS OIC.TF_CONVERSIONS_ID_APN_10pct;
DROP TABLE IF EXISTS OIC.tf_conversions_id_appli_10pct;
DROP TABLE IF EXISTS OIC.tf_conversions_id_cust_contact_10pct;
DROP TABLE IF EXISTS OIC.tf_conversions_id_cust_msisdn_10pct;
DROP TABLE IF EXISTS OIC.tf_conversions_id_ggsn_10pct;
DROP TABLE IF EXISTS OIC.tf_conversions_id_rat_10pct;
DROP TABLE IF EXISTS OIC.tf_localisation_cellules_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_day_201611_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_day_201612_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_day_201701_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_day_201702_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_day_201703_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_day_201704_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_month_201611_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_month_201612_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_month_201701_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_month_201702_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_month_201703_10pct;
DROP TABLE IF EXISTS OIC.tf_customers_sp_month_201704_10pct;
DROP TABLE IF EXISTS OIC.tf_donnees_histo_mensuelles_10pct;
DROP TABLE IF EXISTS OIC.tf_cdr_entrant_10pct;
DROP TABLE IF EXISTS OIC.tf_info_terminaux_10pct;
DROP TABLE IF EXISTS OIC.tf_msim_10pct;
DROP TABLE IF EXISTS OIC.tf_recharge_10pct;
DROP TABLE IF EXISTS OIC.tf_referentiel_terminaux_10pct;
DROP TABLE IF EXISTS OIC.tf_TF_CDR_SORTANT_10pct;
DROP TABLE IF EXISTS OIC.tf_tf_sva_10pct;
DROP TABLE IF EXISTS OIC.tf_tf_transaction_om_10pct;
DROP TABLE IF EXISTS OIC.tf_cdr_traffic_customer_10pct;
DROP TABLE IF EXISTS OIC.tf_cdr_traffic_customer_cell_10pct;
DROP TABLE IF EXISTS OIC.tt_bundle;
DROP TABLE IF EXISTS OIC.tt_cdr_traffic_customer;
DROP TABLE IF EXISTS OIC.tt_cdr_traffic_customer_cell;
