-- CREATE FULL TMP TABLE

-- 0- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TT_REFERENTIEL_TERMINAUX;

CREATE TABLE OIC.TT_REFERENTIEL_TERMINAUX (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

-- 1- ACTIF_DATA_ET_DATE_ACTIVATION
DROP TABLE IF EXISTS OIC.TT_ACTIF_DATA_ET_DATE_ACTIVATION;

CREATE TABLE OIC.TT_ACTIF_DATA_ET_DATE_ACTIVATION (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;



-- 2- BUNDLE
DROP TABLE IF EXISTS OIC.TT_BUNDLE;

CREATE TABLE OIC.TT_BUNDLE (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 3- Data_OCI	
DROP TABLE IF EXISTS OIC.TT_Data_OCI;

CREATE TABLE OIC.TT_Data_OCI (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 4- DONNEES_HISTO_MENSUELLES
DROP TABLE IF EXISTS OIC.TT_DONNEES_HISTO_MENSUELLES;

CREATE TABLE OIC.TT_DONNEES_HISTO_MENSUELLES (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 5- ENTRANT	
DROP TABLE IF EXISTS OIC.TT_ENTRANT;

CREATE TABLE OIC.TT_ENTRANT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 6- INFO_TERMINAUX	
DROP TABLE IF EXISTS OIC.TT_INFO_TERMINAUX;

CREATE TABLE OIC.TT_INFO_TERMINAUX (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 7- MSIM	
DROP TABLE IF EXISTS OIC.TT_MSIM;

CREATE TABLE OIC.TT_MSIM (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 8- RECHARGE	
DROP TABLE IF EXISTS OIC.TT_RECHARGE;

CREATE TABLE OIC.TT_RECHARGE (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 9- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TT_REFERENTIEL_TERMINAUX;

CREATE TABLE OIC.TT_REFERENTIEL_TERMINAUX (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 10- SORTANT
DROP TABLE IF EXISTS OIC.TT_SORTANT;

CREATE TABLE OIC.TT_SORTANT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 11- SVA	
DROP TABLE IF EXISTS OIC.TT_SVA;

CREATE TABLE OIC.TT_SVA (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 12- TRANSACTION_OM
DROP TABLE IF EXISTS OIC.TT_TRANSACTION_OM;

CREATE TABLE OIC.TT_TRANSACTION_OM (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

