-- CREATE FULL TMP TABLE

CREATE TABLE OIC.TT_BUNDLE (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS PARQUET;

LOAD DATA LOCAL PATH 'gs:///oic-bucket/BUNDLE/201611/BUNDLE_0.txt' INTO TABLE OIC.TT_BUNDLE;

SET hive.cli.print.header=true;

SELECT * FROM OIC.TT_BUNDLE LIMIT 10;


