-- 0- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TT_REFERENTIEL_TERMINAUX;

CREATE TABLE OIC.TT_REFERENTIEL_TERMINAUX (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

-- 1- ACTIF_DATA_ET_DATE_ACTIVATION
DROP TABLE IF EXISTS OIC.TT_ACTIF_DATA_ET_DATE_ACTIVATION_10PCT;

CREATE TABLE OIC.TT_ACTIF_DATA_ET_DATE_ACTIVATION_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;



-- 2- BUNDLE
DROP TABLE IF EXISTS OIC.TT_BUNDLE_10PCT;

CREATE TABLE OIC.TT_BUNDLE_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 3- Data_OCI	
DROP TABLE IF EXISTS OIC.TT_Data_OCI_10PCT;

CREATE TABLE OIC.TT_Data_OCI_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 4- DONNEES_HISTO_MENSUELLES
DROP TABLE IF EXISTS OIC.TT_DONNEES_HISTO_MENSUELLES_10PCT;

CREATE TABLE OIC.TT_DONNEES_HISTO_MENSUELLES_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 5- ENTRANT	
DROP TABLE IF EXISTS OIC.TT_ENTRANT_10PCT;

CREATE TABLE OIC.TT_ENTRANT_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 6- INFO_TERMINAUX	
DROP TABLE IF EXISTS OIC.TT_INFO_TERMINAUX_10PCT;

CREATE TABLE OIC.TT_INFO_TERMINAUX_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 7- MSIM	
DROP TABLE IF EXISTS OIC.TT_MSIM_10PCT;

CREATE TABLE OIC.TT_MSIM_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 8- RECHARGE	
DROP TABLE IF EXISTS OIC.TT_RECHARGE_10PCT;

CREATE TABLE OIC.TT_RECHARGE_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 9- REFERENTIEL_TERMINAUX
DROP TABLE IF EXISTS OIC.TT_REFERENTIEL_TERMINAUX_10PCT;

CREATE TABLE OIC.TT_BUNDLE_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 10- SORTANT
DROP TABLE IF EXISTS OIC.TT_SORTANT_10PCT;

CREATE TABLE OIC.TT_SORTANT_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 11- SVA	
DROP TABLE IF EXISTS OIC.TT_SVA_10PCT;

CREATE TABLE OIC.TT_SVA_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;


-- 12- TRANSACTION_OM
DROP TABLE IF EXISTS OIC.TT_TRANSACTION_OM_10PCT;

CREATE TABLE OIC.TT_TRANSACTION_OM_10PCT (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
