-- CREATE FULL TMP TABLE

CREATE DATABASE OIC;

DROP TABLE IF EXISTS OIC.TT_BUNDLE_BIS;

CREATE TABLE OIC.TT_BUNDLE_BIS (
  DATE_SOUSCRIPTIONMSISDN STRING,
  TYPE_SOUSCRIPTION STRING,
  NOMBRE_SOUSCRIPTION STRING,
  MONTANT_SOUSCRIPTION STRING
  )
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\073'
LINES TERMINATED BY '\n'
STORED AS PARQUET;


val my_file = sc.textFile("gs://oic-bucket/BUNDLE/201611/BUNDLE_2.txt") 

LOAD DATA INPATH 'gs://oic-bucket/BUNDLE/201611/BUNDLE_0.txt' INTO TABLE OIC.TT_BUNDLE;

SET hive.cli.print.header=true;

SELECT * FROM OIC.TT_BUNDLE LIMIT 10;


